-- MySQL Script generated by MySQL Workbench
-- Пт 19 апр 2019 17:16:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `location` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `location` (
  `idlocation` INT NOT NULL AUTO_INCREMENT,
  `idsity` INT NULL,
  `rejion` VARCHAR(45) NULL,
  `sity` VARCHAR(45) NULL,
  PRIMARY KEY (`idlocation`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `address` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `address` (
  `idaddress` INT NOT NULL AUTO_INCREMENT,
  `sity` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  PRIMARY KEY (`idaddress`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `type_auto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `type_auto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `type_auto` (
  `idtable1` INT NOT NULL AUTO_INCREMENT,
  `typeauto` VARCHAR(45) NULL,
  PRIMARY KEY (`idtable1`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `title`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `title` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `title` (
  `idtitle` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NULL,
  PRIMARY KEY (`idtitle`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `parametr_auto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `parametr_auto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `parametr_auto` (
  `idparametr_auto` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(25) NULL,
  `owners` VARCHAR(4) NULL,
  `type_avto` VARCHAR(15) NULL,
  `doors` INT NULL,
  `power` INT NULL,
  `type_power` VARCHAR(10) NULL,
  `run` INT NULL,
  `color` VARCHAR(25) NULL,
  `drive` VARCHAR(10) NULL,
  `rulel` VARCHAR(7) NULL,
  `good` VARCHAR(10) NULL,
  `vin` VARCHAR(19) NULL,
  PRIMARY KEY (`idparametr_auto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `by`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `by` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `by` (
  `idby` INT NOT NULL AUTO_INCREMENT,
  `location_idlocation` INT NOT NULL,
  `address_idaddress` INT NOT NULL,
  `create_date` INT NULL,
  `type_auto_idtable1` INT NOT NULL,
  `price` VARCHAR(10) NULL,
  `phone` INT NULL,
  `title_idtitle` INT NOT NULL,
  `time` INT NULL,
  `description` BLOB NULL,
  `parametr_auto_idparametr_auto` INT NOT NULL,
  PRIMARY KEY (`idby`, `location_idlocation`, `address_idaddress`, `type_auto_idtable1`, `title_idtitle`, `parametr_auto_idparametr_auto`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pictures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pictures` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pictures` (
  `idpictures` INT NOT NULL AUTO_INCREMENT,
  `100x75` VARCHAR(46) NULL,
  `140x105` VARCHAR(46) NULL,
  `240x180` VARCHAR(46) NULL,
  `432x324` VARCHAR(46) NULL,
  `640x480` VARCHAR(46) NULL,
  `by_idby` INT NOT NULL,
  `by_location_idlocation` INT NOT NULL,
  `by_address_idaddress` INT NOT NULL,
  `by_type_auto_idtable1` INT NOT NULL,
  PRIMARY KEY (`idpictures`, `by_idby`, `by_location_idlocation`, `by_address_idaddress`, `by_type_auto_idtable1`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
